mysite/interviews/urls.py
from django.conf.urls import url
from . import views

app_name = 'interviews'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^newest/$', views.newest, name='newest'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('interviews.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
]

mysite/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^cal/$', views.calculator, name='cal'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^admin/$', views.admin, name='admin'),
    url(r'^question-list-json/$', views.question_list_json, name='question_list_json'),

]

mysite/interviews/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class SiteNotice(models.Model):
    notice = models.CharField(max_length=200)
    link = models.CharField(max_length=200)

    def __str__(self):
        return self.notice + " : " + self.link

mysite/polls/models.py
from __future__ import unicode_literals
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/interviews/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404
from models import SiteNotice
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

# Create your views here.


def index(request):
    site_notice = get_object_or_404(SiteNotice)
    boards = ["Facebook", "LinkedIn", "Amazon", "Google", "Uber", "Airbnb"]
    example = {
        "2016-Jun-07 新鲜OA题目 截",
        "国内30岁，想去美国硅谷工作或者申请CS PHD",
        "Google 6/2 Onsite [已跪]",
        "公司training不好，求助大家",
        "Google 6/14 二轮店面",
        "被一家ICC给拒了",
        "有人收到 Vancouver Interview Event 的吗",
        "M家onsite吐槽下",
        "FB phone要求bug free？",
    }
    content = {
        "site_notice": site_notice,
        "total_num": 0,
        "boards": boards,
        "example": example
    }
    return render(request, 'interviews/index.html', content)

def newest(request):
    items = [{
        "title": "有近期pure storage onsite的吗，求联系一起讨论，毕业前找到工作的最后希望之一！",
        "link": "http://www.1point3acres.com/bbs/forum.php?mod=viewthread&tid=154315&extra=page%3D2%26filter%3Dsortid%26sortid%3D192%26sortid%3D192",
        "time": "2016-6-28 07:11:25",
        "source": "1point3acres",
        "source_link": "http://www.1point3acres.com/bbs/forum-28-1.html",
        "desc": " 如题，求近期一起有去pure storage onsite的同学吗？求一起讨论学习，加qq552017575。有前辈面过的可以在此帖下留下面筋题目，小弟不甚感激。\
渣渣如我一直跪到现在，也面了很多公司了，一直跪，希望早日找到工作，然后把面过的所有面试都发出造福地里，天天都在攒人品，求offer！",
    }] * 10
    content = {
        "items": items,
        "test": "testMsg",
    }
    return render(request, 'interviews/newest.html', content)

mysite/polls/views.py
from django.core.urlresolvers import reverse
from django.db.models import F
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.utils import timezone
from models import Question, Choice
from django.views import generic


# Create your views here.

class IndexView(generic.ListView):
    context_object_name = 'question_list'
    model = Question
    template_name = 'polls/question_list.html'
    paginate_by = 50

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


def calculator(request):
    return render(request, 'cal/calculator.html')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/question_detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/question_results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        # Increase the question's votes by 1 using F() which is a SQL operation
        selected_choice = question.choice_set.filter(pk=request.POST['choice'])
        selected_choice.update(votes=F('votes') + 1)
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/question_detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def admin(request):
    if request.method == 'POST':
        if 'question_text' in request.POST and 'choice1' in request.POST:
            q = Question(question_text=request.POST['question_text'], pub_date=timezone.now())
            q.save()
            c1 = Choice(question=q, choice_text=request.POST['choice1'])
            c1.save()

    return render(request, 'polls/admin.html', {})

def question_list_json(request):
    response = {}
    qs = Question.objects.all()
    for q in qs:
        response[q.id] = q.question_text
        # print q.question_text, q.pub_date

    return JsonResponse(response)

mysite/interviews/templates/interviews/index.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>面经搜索</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    {% load staticfiles %}
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>


    <!--[if lt IE 9]>
        <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="navbar navbar-inverse navbar-extra">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active" id="home">
                        <a href=""><font color="orange">Home</font></a>
                    </li>

                    <li id="newest">
                        <a href="newest/">Newest</a>
                    </li>

                    <li id="flag">
                        <a href="flag/">FLAG</a>
                    </li>
                    <!-- TODO: not hard code -->
                </ul>
            </div><!--/.navbar-collapse -->



        </div>
    </div>

    <header class="site-header jumbotron">
        <div class="site-nav">
            <a href="#about">About</a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h1>面 经 搜 索</h1>
                    <p>北美 IT 岗位面试经验搜索<br>
                        <span class="package-amount">已收录了 <strong>{{ total_num }}</strong> 个一手面经</span>
                    </p>
                    <form class="" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control search clearable" placeholder="搜索关键词，例如：Google Tree">
                            <i class="fa fa-search" id="btn-search"></i>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">

            <div class="board col-xs-12 col-md-12 col-lg-6">
                <div class="board-header">
                    <span>最新面经</span>
                    <a href="#">More</a>
                </div>

                <div class="board-content">
                    {% for row in example %}
                    <div>
                        <a href="#">{{ row }}</a>
                    </div>
                    {% endfor %}
                </div>

            </div>

            {% for board in boards %}
            <div class="board col-xs-12 col-md-6 col-lg-3">
                <div class="board-header">
                    <span>{{ board }}</span>
                    <a href="#">More</a>
                </div>

                <div class="board-content">
                    {% for row in example %}
                    <div>
                        <a href="#">{{ row }}</a>
                    </div>
                    {% endfor %}
                </div>

            </div>
            {% endfor %}

        </div> <!-- / row -->
    </div>

    <footer id="footer" class="footer ">
        <div class="footer-about " id="about">
            <h4>关于 本网站</h4>
            <p>本网站尚在开发中</p>
            <p>有任何建议欢迎反馈到邮件：###@###.com</p>
        </div>
    </footer>

</body>

</html>

mysite/interviews/templates/interviews/newest.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Newest</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    {% load staticfiles %}
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/newest.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/newest.js' %}"></script>


    <!--[if lt IE 9]>
    <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div class="navbar navbar-inverse navbar-extra navbar-fixed-top">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li id="home">
                    <a href="{% url 'interviews:index' %}">Home</a>
                </li>

                <li class="active" id="newest">
                    <a href="newest/"><font color="orange">Newest</font></a>
                </li>

                <li id="flag">
                    <a href="flag/">FLAG</a>
                </li>
                <!-- TODO: not hard code -->
            </ul>
        </div><!--/.navbar-collapse -->
    </div>
</div>

<header class="site-header">
    <div class="container">
        <div class="row">
            <div class="col-xs-8">
                <form class="" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control search clearable" placeholder="搜索关键词，例如：Google Tree">
                        <i class="fa fa-search"></i>
                    </div>
                </form>
            </div>
            <div class="col-xs-1">

            </div>
            <div class="col-xs-3">
                <!--<div class="form-group">-->
                    <!--<select class="form-control">-->
                        <!--<option>Choose one filter</option>-->
                        <!--<option>Facebook</option>-->
                        <!--<option>Linkedin</option>-->
                        <!--<option>Amazon</option>-->
                        <!--<option>Google</option>-->
                        <!--<option>Others</option>-->
                    <!--</select>-->
                <!--</div>-->
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <p>共为您找到XXX个结果</p>

            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row results">
        {% for item in items %}
        <div class="col-xs-7 content-wrapper">
            <div class="content">
            <a class="content-title" href="{{ item.link }}" target="_blank">{{ item.title }}</a>
            <p>
                <span class="content-time">{{ item.time }} - </span>
                <span class="content-desc">{{ item.desc }}</span>
            </p>
            <a class="content-source" href="{{ item.source_link }}" target="_blank">From {{ item.source }}</a>
            </div>
        </div>
        </br>
        </br>
        {% endfor %}
    </div> <!-- / row -->

</div>

</body>

</html>

mysite/polls/templates/cal/calculator.html
<!DOCTYPE html>
<html>
<head>
  <title>HTML Calculator</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'calculator/calculator.css' %}">
  <script language="JavaScript" type="text/javascript" src="{% static 'calculator/calculator.js' %}"></script>

</head>
<body>
  <div id="content">
    <div id="title"></div>
    <div class="screen">
	  <div id="display">0</div>
	</div>
	<div id="buttons-container">
	  <div class="button" onclick="numberOnClick(this)">7</div>
	  <div class="button" onclick="numberOnClick(this)">8</div>
	  <div class="button" onclick="numberOnClick(this)">9</div>
	  <div class="button operator" onclick="operatorOnClick(this)">+</div>
	  <div class="button" onclick="numberOnClick(this)">4</div>
	  <div class="button" onclick="numberOnClick(this)">5</div>
	  <div class="button" onclick="numberOnClick(this)">6</div>
	  <div class="button operator" onclick="operatorOnClick(this)">-</div>
	  <div class="button" onclick="numberOnClick(this)">1</div>
	  <div class="button" onclick="numberOnClick(this)">2</div>
	  <div class="button" onclick="numberOnClick(this)">3</div>
	  <div class="button operator" onclick="operatorOnClick(this)">*</div>
	  <div class="button operator" onclick="operatorOnClick(this)">.</div>
	  <div class="button" onclick="numberOnClick(this)">0</div>
	  <div class="button operator" onclick="operatorOnClick(this)">=</div>
	  <div class="button operator" onclick="operatorOnClick(this)">/</div>
	</div>
  </div>

</body>
<html>

mysite/polls/templates/polls/admin.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Admin</title>
    <meta name="description" content="">
    <meta name="author" content="">


    {% load staticfiles %}
    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <link rel="icon" href="{% static 'img/cmu_icon.ico' %}">

    <!--  Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/admin.css' %}">
    <!--  JS for this template -->
    <script language="JavaScript" type="text/javascript" src="{% static 'js/admin.js' %}"></script>

</head>
<body>
    <h1>I am a admin page for polls, Fuck You!</h1>

    <form class="form-horizontal" role="form" action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="question" class="col-sm-2 control-label">Question: </label>
            <div class="col-sm-10">
                <input class="form-control" id="question" type="text" name="question_text"
                       placeholder="Please Type Question Text...">
            </div>
        </div>
        <div class="form-group">
            <label for="choice1" class="col-sm-2 control-label">Choice 1: </label>
            <div class="col-sm-10">
                <input class="form-control" id="choice1" type="text" name="choice1"
                       placeholder="Please Type Choice Text...">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </div>

    </form>

</body>
</html>

mysite/polls/templates/polls/bootstrap_example.html
<html lang="zh-CN"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style id="style-1-cropbar-clipper">/* Copyright 2014 Evernote Corporation. All rights reserved. */
    .en-markup-crop-options {
        top: 18px !important;
        left: 50% !important;
        margin-left: -100px !important;
        width: 200px !important;
        border: 2px rgba(255,255,255,.38) solid !important;
        border-radius: 4px !important;
    }

    .en-markup-crop-options div div:first-of-type {
        margin-left: 0px !important;
    }
    </style></head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <form class="navbar-form navbar-right">
                <div class="form-group">
                    <input type="text" placeholder="Email" class="form-control">
                </div>
                <div class="form-group">
                    <input type="password" placeholder="Password" class="form-control">
                </div>
                <button type="submit" class="btn btn-success">Sign in</button>
            </form>
        </div><!--/.navbar-collapse -->
    </div>
</nav>

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
    </div>
</div>

<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
        </div>
    </div>

    <hr>

    <footer>
        <p>© Company 2014</p>
    </footer>
</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>


<div id="cntvlive2-is-installed"></div></body></html>

mysite/polls/templates/polls/question_detail.html
<!DOCTYPE html>
<h1>{{question.question_text}}</h1>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method='post'>
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
		<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br/>
	{% endfor %}
	<input type="submit" value="Vote"/>
</form>

mysite/polls/templates/polls/question_list.html
<!DOCTYPE html>
<head>
	<title>Question List</title>

	{% load staticfiles %}
	<script type="text/javascript" src="{% static 'js/question_list.js' %}"></script>
</head>
<body>
	<h1>Fuck you I am from a template</h1>

	{% if question_list %}
		<ul id="question_list">
		{% for question in question_list %}
			<li id="question_{{question.id}}" class="question"><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>No polls are available.</p>
	{% endif %}

</body>

mysite/polls/templates/polls/question_results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>